server:
  port: 8080

logging:
  level:
    ROOT: INFO
    br.com.labexame: DEBUG
spring:  
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      org.hibernate.envers.revision_field_name: ID_REVI
      org.hibernate.envers.revision_type_field_name: ST_REVI
      org.hibernate.envers.store_data_at_delete: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/lab-exame?useSSL=false
    username: root
    password: jesuscristo
    hikari:
      minimum-idle: 5
      # NUMERO MAXIMO DO POOL DE CONEXAO
      maximum-pool-size: 100
      idle-timeout: 60000
      pool-name: labexecCP
      # CONFIGURANDO PARA 60 SEG
      connection-timeout: 120000
      max-lifetime: 2000000
      data-source-properties:
        cache-prep-stmts: true
        prep-stmp-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
        use-server-prep-stmts: true

  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false
  profiles:
    active: native