server:
  port: 8080

logging:
  level:
    ROOT: INFO
    br.com.labexame: DEBUG
spring:  
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      org.hibernate.envers.revision_field_name: ID_REVI
      org.hibernate.envers.revision_type_field_name: ST_REVI
      org.hibernate.envers.store_data_at_delete: true
  datasource:
    
    #mysql://i3areu87xgpj1nru:veo6vpvnr6zusy3t@lolyz0ok3stvj6f0.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/u7uk2rg02mlhgmid
    
    type: com.zaxxer.hikari.HikariDataSource
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      minimum-idle: 5
      # NUMERO MAXIMO DO POOL DE CONEXAO
      maximum-pool-size: 100
      idle-timeout: 60000
      pool-name: clientesCP
      # CONFIGURANDO PARA 60 SEG
      connection-timeout: 120000
      max-lifetime: 2000000
      data-source-properties:
        cache-prep-stmts: true
        prep-stmp-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
        use-server-prep-stmts: true

  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false
  profiles:
    active: native
  
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml  
    enabled: true
